//! Stable opcode ordering required by the input bytecode format.
//! Keep the byte values compatible while exposing them as a Zig enum.

const std = @import("std");

pub const Opcode = enum(u8) {
    invalid,
    push_value,
    push_const,
    fclosure,
    undefined_value,
    null_value,
    push_this,
    push_false,
    push_true,
    object,
    this_func,
    arguments,
    new_target,
    drop,
    nip,
    dup,
    dup1,
    dup2,
    insert2,
    insert3,
    perm3,
    perm4,
    swap,
    rot3l,
    call_constructor,
    call,
    call_method,
    array_from,
    return_value,
    return_undef,
    throw,
    regexp,
    get_field,
    get_field2,
    put_field,
    get_array_el,
    get_array_el2,
    put_array_el,
    get_length,
    get_length2,
    define_field,
    define_getter,
    define_setter,
    set_proto,
    get_loc,
    put_loc,
    get_arg,
    put_arg,
    get_var_ref,
    put_var_ref,
    get_var_ref_nocheck,
    put_var_ref_nocheck,
    if_false,
    if_true,
    goto,
    catch_value,
    gosub,
    ret,
    for_in_start,
    for_of_start,
    for_of_next,
    neg,
    plus,
    dec,
    inc,
    post_dec,
    post_inc,
    not,
    lnot,
    typeof_value,
    delete_property,
    mul,
    div,
    mod,
    add,
    sub,
    pow,
    shl,
    sar,
    shr,
    lt,
    lte,
    gt,
    gte,
    instanceof,
    in_operator,
    eq,
    neq,
    strict_eq,
    strict_neq,
    and_op,
    xor,
    or_op,
    nop,
    push_minus1,
    push_0,
    push_1,
    push_2,
    push_3,
    push_4,
    push_5,
    push_6,
    push_7,
    push_i8,
    push_i16,
    push_const8,
    fclosure8,
    push_empty_string,
    get_loc8,
    put_loc8,
    get_loc0,
    get_loc1,
    get_loc2,
    get_loc3,
    put_loc0,
    put_loc1,
    put_loc2,
    put_loc3,
    get_arg0,
    get_arg1,
    get_arg2,
    get_arg3,
    put_arg0,
    put_arg1,
    put_arg2,
    put_arg3,
    array_append,
    array_spread,
    object_spread,
    object_keys,
    call_spread,
    function_bind,
    collection_new,
    regexp_new,
    push_global_this,
    call_method_spread,
    array_new,
    add_loc,
    sub_loc,
    await,
    to_bigint,
    byte_array_new,
};

pub const count = @typeInfo(Opcode).@"enum".field_names.len;

test "opcode numbers preserve upstream order and compact opcode groups" {
    try std.testing.expectEqual(@as(u8, 0), @intFromEnum(Opcode.invalid));
    try std.testing.expectEqual(@as(u8, 1), @intFromEnum(Opcode.push_value));
    try std.testing.expectEqual(@as(u8, 93), @intFromEnum(Opcode.nop));
    try std.testing.expectEqual(@as(u8, 94), @intFromEnum(Opcode.push_minus1));
    try std.testing.expectEqual(@as(u8, 95), @intFromEnum(Opcode.push_0));
    try std.testing.expectEqual(@as(u8, 102), @intFromEnum(Opcode.push_7));
    try std.testing.expectEqual(@as(u8, 137), @intFromEnum(Opcode.add_loc));
    try std.testing.expectEqual(@as(u8, 138), @intFromEnum(Opcode.sub_loc));
    try std.testing.expectEqual(@as(u8, 139), @intFromEnum(Opcode.await));
    try std.testing.expectEqual(@as(u8, 140), @intFromEnum(Opcode.to_bigint));
    try std.testing.expectEqual(@as(u8, 141), @intFromEnum(Opcode.byte_array_new));
    try std.testing.expectEqual(@as(usize, 142), count);
}
